# Generated by Django 2.2 on 2021-07-02 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_column='category_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_column='product_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('code', models.CharField(db_column='code', max_length=50)),
                ('unit_price', models.IntegerField(db_column='unit_price')),
                ('current_stock', models.IntegerField(db_column='current_stock')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_management.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
