# Generated by Django 2.2 on 2021-07-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
    ]
