# Generated by Django 2.2 on 2021-07-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_auto_20210703_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Orders'},
        ),
    ]
