# Generated by Django 2.2 on 2021-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_auto_20210703_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qr_code',
            field=models.ImageField(blank=True, db_column='QR_code', null=True, upload_to='qrcode'),
        ),
    ]
