# Generated by Django 2.2 on 2021-07-04 08:34

from django.db import migrations, models
import order_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_customer_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.IntegerField(db_column='invoice_no', default=order_management.models.generate_invoice_no),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, db_column='QR_code', null=True, upload_to='qrcode'),
        ),
    ]
